global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'exchange-hub'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - backend:8080
